from __future__ import annotations

import io
import json
import os
import sys
import tempfile
import unittest
from contextlib import redirect_stdout
from pathlib import Path
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts" / "lib"))

from play.audit import adapters, card, frontmatter, host, rules, store  # noqa: E402
from play.audit.cli import main, resolve_target  # noqa: E402
from play.audit.runner import safe_audit  # noqa: E402

FIXTURES = ROOT / "tests" / "fixtures" / "audit"
JUDGMENT_IDS = {rule.id for rule in rules.RULES.values() if rule.cls == "judgment"}
FACT_IDS = {rule.id for rule in rules.RULES.values() if rule.cls == "fact"}


def audit(name: str, **kwargs):
    kwargs.setdefault("read_adapters", False)
    kwargs.setdefault("persist", False)
    return safe_audit(FIXTURES / name, reference=f"audit/{name}", **kwargs)


def ids(envelope, section: str) -> set[str]:
    return {item["id"] for item in envelope[section]}


class NoProbe(unittest.TestCase):
    """Host probes spawn `--version`; tests never do."""

    def setUp(self) -> None:
        self._environ = patch.dict(os.environ, {"PLAY_AUDIT_NO_PROBE": "1"})
        self._environ.start()

    def tearDown(self) -> None:
        self._environ.stop()


class RuleRegistryTest(unittest.TestCase):
    def test_every_rule_has_a_class_owner_and_fix(self) -> None:
        for rule in rules.RULES.values():
            self.assertIn(rule.cls, {"fact", "judgment"}, rule.id)
            self.assertTrue(rule.owner.startswith("rote-"), rule.id)
            self.assertTrue(rule.fix, rule.id)
            self.assertTrue(rule.message, rule.id)


class FrontmatterTest(unittest.TestCase):
    def test_extracts_yaml_from_jsdoc(self) -> None:
        front = frontmatter.extract((FIXTURES / "clean" / "main.ts").read_text())
        self.assertIsNone(front.error)
        self.assertEqual(["repo"], front.parameter_names)
        self.assertTrue(front.parameters_top_level)
        self.assertEqual("steps_with_presentation", front.execution_model)
        self.assertIn("count", front.steps)
        self.assertIn("new FlowOutput", front.body)

    def test_missing_block_is_an_error_not_a_guess(self) -> None:
        front = frontmatter.extract("const x = 1;\n")
        self.assertEqual("no @rote-frontmatter block", front.error)
        self.assertEqual({}, front.data)

    def test_usage_notes_after_the_closing_marker_are_ignored(self) -> None:
        source = (
            "/**\n * @rote-frontmatter\n * ---\n * name: noted\n * description: d\n"
            " * metadata:\n *   version: 1.0.0\n * parameters: []\n * steps: {}\n * ---\n *\n"
            " * Usage:\n *   rote play run ~/.rote/flows/noted/main.ts key=value\n */\nconst x = 1;\n"
        )
        front = frontmatter.extract(source)
        self.assertIsNone(front.error)
        self.assertEqual("noted", front.data["name"])
        self.assertIn("const x = 1", front.body)

    def test_nested_parameters_and_suppressions(self) -> None:
        front = frontmatter.extract((FIXTURES / "nested-params" / "main.ts").read_text())
        self.assertFalse(front.parameters_top_level)
        self.assertEqual(["name"], front.parameter_names)
        self.assertEqual({"PARAMETERS_UNDER_METADATA": "generated by an older rote; works by fallback"}, front.suppressions)


class FixtureFindingsTest(NoProbe):
    def test_clean_play_has_nothing_to_say(self) -> None:
        envelope = audit("clean")
        self.assertEqual("ok", envelope["status"])
        self.assertEqual([], envelope["facts"])
        self.assertEqual([], envelope["judgments"])
        self.assertEqual([], envelope["unknowns"])
        self.assertIn("git", envelope["reach"]["commands"], "shell resource commands count as reach")

    def test_partial_scan(self) -> None:
        envelope = audit("partial-scan")
        self.assertEqual({"FANOUT_OVER_PREVIEW", "STEP_NO_TIMEOUT"}, ids(envelope, "facts"))
        self.assertEqual({"UNRELIABLE_EXIT_STATUS", "TOOL_DECLARED_UNUSED"}, ids(envelope, "judgments"))
        unused = next(item for item in envelope["judgments"] if item["id"] == "TOOL_DECLARED_UNUSED")
        self.assertEqual("rsync", unused["evidence"]["command"])
        self.assertEqual("rote-troubleshooting", next(f for f in envelope["facts"] if f["id"] == "FANOUT_OVER_PREVIEW")["owner"])

    def test_stranded_body(self) -> None:
        envelope = audit("stranded")
        self.assertEqual({"BODY_STRANDED", "DEPS_TOML_MISSING", "PARAMETERS_UNDER_METADATA", "STEP_NO_TIMEOUT"}, ids(envelope, "facts"))
        self.assertEqual({"PARAM_UNREFERENCED"}, ids(envelope, "judgments"))
        self.assertEqual([("INLINE_BODY_UNREAD", "steps.scan")], [(u["kind"], u["subject"]) for u in envelope["unknowns"]])
        self.assertEqual(["scan"], envelope["reach"]["unread_bodies"])

    def test_python_floor(self) -> None:
        envelope = audit("pyfloor")
        facts = envelope["facts"]
        self.assertEqual({"INTERPRETER_FLOOR_MISSING", "PY_FLOOR_TOO_LOW"}, ids(envelope, "facts"))
        needs = sorted((f["evidence"]["construct"], f["evidence"]["needs"]) for f in facts if f["id"] == "PY_FLOOR_TOO_LOW")
        self.assertEqual([("a PEP 604 union in an evaluated annotation", "3.10"), ("an unguarded `import tomllib`", "3.11")], needs)
        self.assertEqual([], envelope["judgments"])

    def test_python_floor_negative_controls(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp) / "neg"
            (root / "resources").mkdir(parents=True)
            (root / "main.ts").write_text((FIXTURES / "pyfloor" / "main.ts").read_text())
            (root / "deps.toml").write_text(
                'schema_version = 1\n\n[[tools]]\nid = "python3"\ncommand = "python3"\nrequired = true\nversion_requirement = ">=3.11.0"\n')
            (root / "resources" / "check.py").write_text(
                "from __future__ import annotations\n"
                "import sys\n"
                "try:\n    import tomllib\nexcept ImportError:\n    tomllib = None\n"
                "x = a | b\n"
                "def f(v: int | None) -> str | None:\n    return None\n")
            envelope = safe_audit(root, reference="audit/neg", read_adapters=False, persist=False)
        self.assertNotIn("PY_FLOOR_TOO_LOW", ids(envelope, "facts"))
        self.assertNotIn("INTERPRETER_FLOOR_MISSING", ids(envelope, "facts"))

    def test_missing_resource_and_home_path(self) -> None:
        envelope = audit("missing-resource")
        self.assertEqual({"ABSOLUTE_HOME_PATH", "DEPENDS_ON_UNKNOWN", "RESOURCE_MISSING"}, ids(envelope, "facts"))

    def test_spawned_commands(self) -> None:
        envelope = audit("spawns")
        self.assertEqual({"DENO_COMMAND_UNDECLARED", "SUBPROCESS_UNDECLARED"}, ids(envelope, "facts"))
        self.assertEqual({"DYNAMIC_COMMAND_UNRESOLVABLE"}, ids(envelope, "judgments"))
        commands = {f["evidence"]["command"] for f in envelope["facts"]}
        self.assertEqual({"gh", "docker"}, commands, "python3 is declared and must not be flagged")
        self.assertTrue(all("line" in f["location"] for f in envelope["facts"]))

    def test_suppression_moves_a_fact_out_of_facts(self) -> None:
        envelope = audit("nested-params")
        self.assertEqual([], envelope["facts"])
        self.assertEqual(["PARAMETERS_UNDER_METADATA"], [s["id"] for s in envelope["suppressions"]])
        self.assertEqual(1, envelope["summary"]["suppressed"])


class ConsumerCardTest(NoProbe):
    def test_card_never_shows_judgments_rule_ids_or_counts(self) -> None:
        for name in ("partial-scan", "stranded", "spawns", "pyfloor"):
            envelope = audit(name)
            text = card(envelope)
            for rule_id in JUDGMENT_IDS | FACT_IDS:
                self.assertNotIn(rule_id, text, f"{rule_id} leaked into the card for {name}")
            self.assertNotIn("judgment", text.lower())
            self.assertNotIn("fact", text.lower().replace("artifacts", ""))
            self.assertIn("Can it run here", text)

    def test_card_states_unread_bodies(self) -> None:
        text = card(audit("stranded"))
        self.assertIn("runs code this inspection could not read", text)

    def test_card_is_empty_when_audit_unavailable(self) -> None:
        envelope = safe_audit(Path("/nonexistent/play"), reference="x/y", read_adapters=False, persist=False)
        self.assertEqual("ok", envelope["status"], "a missing main.ts is an unknown, not a crash")
        from play.audit.runner import unavailable
        self.assertEqual("", card(unavailable("x/y", "boom")))


class FailSafeTest(NoProbe):
    def test_every_extractor_raising_still_yields_an_envelope(self) -> None:
        boom = patch("play.audit.steps.analyze", side_effect=RuntimeError("steps exploded"))
        boom2 = patch("play.audit.bodies.analyze", side_effect=RuntimeError("bodies exploded"))
        boom3 = patch("play.audit.host.resolve", side_effect=RuntimeError("host exploded"))
        with boom, boom2, boom3:
            envelope = audit("clean")
        self.assertEqual("ok", envelope["status"])
        kinds = {(u["kind"], u["subject"]) for u in envelope["unknowns"]}
        self.assertIn(("EXTRACTOR_FAILED", "steps"), kinds)
        self.assertIn(("EXTRACTOR_FAILED", "bodies"), kinds)
        self.assertIn(("EXTRACTOR_FAILED", "host"), kinds)
        self.assertEqual([], envelope["facts"])
        self.assertTrue(envelope["summary"]["can_run_here"])

    def test_package_load_failure_is_audit_unavailable(self) -> None:
        with patch("play.audit.package.load", side_effect=OSError("disk gone")):
            envelope = audit("clean")
        self.assertEqual("audit_unavailable", envelope["status"])
        self.assertIn("disk gone", envelope["reason"])
        self.assertEqual("", card(envelope))

    def test_extractor_timeout_is_an_unknown(self) -> None:
        import time as _time

        def slow(package):
            _time.sleep(5)

        with patch("play.audit.bodies.analyze", side_effect=slow), patch("play.audit.runner._TASK_TIMEOUT_SECONDS", 0.2):
            envelope = audit("clean")
        self.assertEqual("ok", envelope["status"])
        self.assertTrue(any(u["subject"] == "bodies" and "timed out" in u["reason"] for u in envelope["unknowns"]))


class HostProfileTest(NoProbe):
    def test_stock_macos_rejects_a_declared_floor_above_3_9(self) -> None:
        envelope = audit("spawns", profile="stock-macos")
        need = next(n for n in envelope["host"]["needs"] if n["name"] == "python3")
        self.assertEqual("version_low", need["status"])
        self.assertFalse(envelope["summary"]["can_run_here"])
        self.assertIn("3.9.6", envelope["summary"]["cannot_run_reason"])

    def test_ubuntu_profile_accepts_it(self) -> None:
        envelope = audit("spawns", profile="ubuntu-lts")
        self.assertTrue(envelope["summary"]["can_run_here"])

    def test_requirement_parsing(self) -> None:
        self.assertTrue(host.satisfies("Python 3.12.3", ">=3.10.0"))
        self.assertFalse(host.satisfies("3.9.6", ">=3.10"))
        self.assertIsNone(host.satisfies(None, ">=3.10"))
        self.assertIsNone(host.satisfies("3.9.6", None))


class AdapterCorrelationTest(NoProbe):
    def test_operation_and_provenance_facts(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp) / "weather"
            root.mkdir()
            (root / "main.ts").write_text(
                "/**\n * @rote-frontmatter\n * ---\n * name: weather\n * description: w\n"
                " * metadata:\n *   version: 1.0.0\n *   execution_model: steps_with_presentation\n"
                " * requires_endpoints:\n *   - adapter/open-meteo\n"
                " * adapter_sources:\n *   adapter/open-meteo: robpumpaf/open-meteo\n"
                " * parameters: []\n * steps:\n *   forecast:\n *     endpoint: adapter/open-meteo\n"
                " *     method: get_v2_forecast\n *     timeout_ms: 5000\n * ---\n */\n"
                "const sdk = await import('__ROTE_PRESENTATION_SDK__');\n")

            def reader(adapter_id: str) -> adapters.AdapterInfo:
                return adapters.AdapterInfo(adapter_id, operations={"get_v1_forecast"}, provenance="debasishg/open-meteo", fingerprint="mcp_x")

            envelope = safe_audit(root, reference="audit/weather", adapter_reader=reader, persist=False)
        self.assertEqual({"ADAPTER_OPERATION_UNKNOWN", "ADAPTER_SOURCE_PROVENANCE_DIFFERS"}, ids(envelope, "facts"))
        self.assertEqual(["adapter/open-meteo"], envelope["reach"]["services"])

    def test_unreadable_adapter_is_an_unknown(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp) / "svc"
            root.mkdir()
            (root / "main.ts").write_text(
                "/**\n * @rote-frontmatter\n * ---\n * name: svc\n * description: s\n * metadata:\n *   version: 1.0.0\n"
                " * requires_endpoints:\n *   - adapter/ghost\n * parameters: []\n * steps: {}\n * ---\n */\n")

            def reader(adapter_id: str) -> adapters.AdapterInfo:
                return adapters.AdapterInfo(adapter_id, error="rote adapter info ghost: not installed")

            envelope = safe_audit(root, reference="audit/svc", adapter_reader=reader, persist=False)
        self.assertEqual([("ADAPTER_NOT_READABLE", "adapter/ghost")], [(u["kind"], u["subject"]) for u in envelope["unknowns"]])
        self.assertEqual([], envelope["facts"])


class StoreTest(NoProbe):
    def test_persist_history_load_and_delta(self) -> None:
        with tempfile.TemporaryDirectory() as temp, patch.dict(os.environ, {"PLAY_HOME": temp}):
            first = audit("partial-scan", persist=True)
            self.assertIsNotNone(first["history_ref"])
            self.assertTrue(Path(first["history_ref"]).is_file())
            loaded = store.load("audit/partial-scan")
            assert loaded is not None
            self.assertEqual(first["subject"]["digest"], loaded["subject"]["digest"])
            by_digest = store.load("audit/partial-scan", digest=first["subject"]["digest"])
            self.assertIsNotNone(by_digest)
            entries = store.history("audit/partial-scan")
            self.assertEqual(["audit"], [e["event"] for e in entries])
            self.assertEqual(2, entries[0]["open_facts"])
            fixed = audit("clean", persist=False)
            delta = store.delta(first, fixed)
            self.assertEqual(4, len(delta["closed"]))
            self.assertEqual([], delta["new"])
            self.assertEqual(first["subject"]["digest"], delta["digest_before"])

    def test_store_failure_is_an_unknown_not_an_error(self) -> None:
        with tempfile.TemporaryDirectory() as temp, patch.dict(os.environ, {"PLAY_HOME": str(Path(temp) / "file")}):
            (Path(temp) / "file").write_text("not a directory")
            envelope = audit("clean", persist=True)
        self.assertEqual("ok", envelope["status"])
        self.assertTrue(any(u["kind"] == "STORE_FAILED" for u in envelope["unknowns"]))


class CliTest(NoProbe):
    def _run(self, *argv: str) -> tuple[int, str]:
        buffer = io.StringIO()
        with redirect_stdout(buffer):
            code = main(list(argv))
        return code, buffer.getvalue()

    def test_default_is_the_card_and_exit_is_always_zero(self) -> None:
        code, out = self._run(str(FIXTURES / "partial-scan"), "--no-adapters", "--no-store")
        self.assertEqual(0, code)
        self.assertIn("Shape", out)
        self.assertNotIn("UNRELIABLE_EXIT_STATUS", out)

    def test_author_and_json_modes(self) -> None:
        code, out = self._run(str(FIXTURES / "stranded"), "--author", "--no-adapters", "--no-store")
        self.assertEqual(0, code)
        self.assertIn("BODY_STRANDED", out)
        self.assertIn("→ rote-flow-authoring", out)
        code, out = self._run(str(FIXTURES / "stranded"), "--json", "--no-adapters", "--no-store")
        self.assertEqual("play-audit/1", json.loads(out)["schema"])

    def test_unresolvable_reference_is_unavailable_not_a_crash(self) -> None:
        with patch.dict(os.environ, {"ROTE_HOME": tempfile.mkdtemp()}):
            code, out = self._run("nobody/nothing@1.0.0", "--json", "--no-store")
        self.assertEqual(0, code)
        self.assertEqual("audit_unavailable", json.loads(out)["status"])

    def test_history_and_show(self) -> None:
        with tempfile.TemporaryDirectory() as temp, patch.dict(os.environ, {"PLAY_HOME": temp}):
            self._run(str(FIXTURES / "pyfloor"), "--no-adapters")
            code, out = self._run("history", "audit/pyfloor")
            self.assertEqual(0, code)
            self.assertIn("facts 3", out)
            code, out = self._run("show", "audit/pyfloor", "--author")
            self.assertIn("PY_FLOOR_TOO_LOW", out)
            code, out = self._run("history", "audit/never")
            self.assertIn("no audits recorded", out)

    def test_resolve_target_forms(self) -> None:
        root, reference = resolve_target(str(FIXTURES / "clean" / "main.ts"))
        self.assertEqual(FIXTURES / "clean", root)
        self.assertEqual("audit/clean", reference)
        with patch.dict(os.environ, {"ROTE_HOME": tempfile.mkdtemp()}):
            root, reference = resolve_target("https://play.modiqo.ai/owner/name@0.1.0")
        self.assertIsNone(root)
        self.assertEqual("owner/name", reference)


if __name__ == "__main__":
    unittest.main()
