/**
 * @rote-frontmatter
 * ---
 * name: nested-params
 * description: Parameters nested under metadata, suppressed by the author
 * metadata:
 *   version: 0.1.0
 *   execution_model: steps_with_presentation
 *   parameters:
 *   - name: name
 *     type: string
 *     required: true
 * audit:
 *   allow:
 *   - rule: PARAMETERS_UNDER_METADATA
 *     reason: generated by an older rote; works by fallback
 * steps:
 *   hello:
 *     type: process.exec
 *     argv:
 *     - echo
 *     - $name
 *     timeout_ms: 1000
 * ---
 */
const sdk = await import("__ROTE_PRESENTATION_SDK__");
const { FlowOutput } = sdk; const out = new FlowOutput(); out.human("x"); out.summary("x"); out.result({});
